Baseflow/flutter-permission-handler

ios/Classes/PermissionManager.swift
ios/Classes/SwiftPermissionHandlerPlugin.swift

Bug fix
On iOS it is possible to run multiple requests for permissions at the same time. This doesn't match with the Android API
The plugin will throw an exception when you send a second request for permissions while the first request is not yet finished.
Nope
Run example app

Make sure you cannot run multiple permission requests at the same time

---

README.md
example/lib/main.dart
lib/permission_enums.dart
lib/permission_handler.dart
lib/utils/codec.dart

Feature
In current version you separately have to import `permission_enums.dart` to get access to the `PermissionGroup` and `PermissionStatus` enums. 
By converting the project into a library (using the `library`, `part` and `part of` keywords) this will no longer be necessary and the user now only needs to import the `permission_handler.dart`.
Yes (developers using the plugin need to remove the existing `import 'package:permission_handler/permission_enums.dart';` line from their code to be able to compile again.
Run the example application:
```shell
cd example
flutter run
```

Converted plugin to library

---

CHANGELOG.md
README.md
example/lib/main.dart
ios/permission_handler.podspec
lib/permission_handler.dart
pubspec.yaml

Prepare for version 1.0.1:
- Update version numbers
- Update Changelog
- Fix code formatting (as reported on pub.dartlang.org)

Bump version number and update changelog

---

.travis.yml

Feature
Build currently doesn't analyze the code.
Build also runs static analyses as part of the build script.
No
Run build on travis

Add analyze task to build configuration

---

android/build.gradle

Bug fix (Android only)
When including other libraries which reference a different version of the `com.android.support:support-compat` package the application won't compile.
Fixed configuration in gradle file to prevent these kind of errors.
Nope
Run the example project
- Fixes #28

Fix error with dependency on Android Support

---

example/ios/Podfile
example/ios/Runner.xcodeproj/project.pbxproj
ios/Classes/PermissionManager.swift

Bug
Apple introduced a breaking change in the latest version of iOS SDK, causing the build to fail.
Correctly call the iOS SDK so the build doesn't fail anymore.
No
Run the example project
- Fixes #49

Fix build error on latest Xcode (iOS 12)

---

ios/permission_handler.podspec

Specify the swift version to avoid compile error when use cocoapods 1.6

specify the swift version

---

example/ios/Runner.xcodeproj/project.pbxproj
example/lib/main.dart
ios/Classes/PermissionManager.swift

Bug fix
Currently calling the `openAppSettings` method always returns `false` on iOS.
The return value is fixed and will correctly return `true` when opening the AppSettings was successful or `false` if not.
No
Run the test application and open the App settings. State should be reported to the debug console.
- Fixes #52

Fixed false negative when opening AppSettings on iOS

---

android/src/main/java/com/baseflow/permissionhandler/PermissionHandlerPlugin.java

Bug fix
When requesting permissions for the `PermissionGroup.microphone` on Android the result returned is based on the `PermissionGroup.speech`.
Updated the code so the result is based on `PermissionGroup.microphone` and `PermissionGroup.speech`.
No
Run the example application.
- Fixes #67

Make sure permission result matches requested group

---

lib/src/permission_enums.dart

Changing description from incorrect "user granted restricted access" to the description found on the Apple Developer site:
"kCLAuthorizationStatusRestricted
This app is not authorized to use location services.
The user cannot change this app’s status, possibly due to active restrictions such as parental controls being in place."
https://developer.apple.com/documentation/corelocation/clauthorizationstatus/kclauthorizationstatusrestricted
This is my first git pull request.  Please be kind. :)
Docs update.
Misleading description.
More clear description.
No.
No special testing required.  Only a comment is changed.
See description above.

Clarify PermissionStatus.restricted description.

---

lib/src/utils/codec.dart

Code maintenance
Prints call arguments when `decodePermissionRequestResult` is called.
Does not print call arguments when `decodePermissionRequestResult` is called.
No.

Remove print statement

---

android/build.gradle
example/android/build.gradle
example/android/gradle/wrapper/gradle-wrapper.properties

Infrastructure
Uses old gradle versions, Android Studio will prompt developer to update
New gradle infrastructure, Android Studio can start without prompts.
No
Open AS

Upgrade gradle infrastructure.

---

android/src/main/java/com/baseflow/permissionhandler/PermissionHandlerPlugin.java

To prevent issues with the location_permissions plugin, as it's being used from geolocator.
Conflicts with location_permissions.. details in #111 
Change request code.
include geolcoator in example - test permissions like call or storage,
Consider to set proper request codes for all BaseflowIT plugins to avoid any further conflicts.

Android uses request code 24 from now on

---

CHANGELOG.md
android/build.gradle
android/src/main/java/com/baseflow/permissionhandler/PermissionHandlerPlugin.java
example/android/build.gradle
example/ios/Podfile
example/ios/Runner.xcodeproj/project.pbxproj
example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
example/lib/main.dart
ios/Classes/PermissionManager.h
ios/Classes/PermissionManager.m
ios/Classes/strategies/LocationPermissionStrategy.m
ios/Classes/strategies/MediaLibraryPermissionStrategy.m
ios/Classes/strategies/PhonePermissionStrategy.h
ios/Classes/strategies/PhonePermissionStrategy.m
ios/Classes/strategies/SpeechPermissionStrategy.m
lib/src/permission_handler.dart

Feature
checkServiceStatus for phone call capability will always return `notApplicable`, independent of the users' handsets capability to place phone calls.
service status of `enabled` when the handset could in theory place calls.
service status of `notApplicable` when the handset has no ability to call.
This should be (hence the WIP) more fine grained and also check if there's a actual SIM card inserted.
No, as potentially nobody is using getServiceStatus for phone calls
Use a wifi-only tablet plus 2 test phones to explore the different results.
TBD Android: https://stackoverflow.com/questions/5196833/android-device-phone-call-ability
TBD iOS:
https://stackoverflow.com/questions/5094928/detecting-whether-or-not-device-support-phone-calls/11595365#11595365
@mvanbeusekom Need your comment …

Phone service status on iOS & Android

---

android/src/main/java/com/baseflow/permissionhandler/PermissionHandlerPlugin.java

Bug fix.
When a permission request fails, an invalid log message is produced.
This seems to be a artifact from the Kotlin implementation which supported inline string formatting.
Error logs do not contain `$permission` but the correct permission name.
No.
Introduce errors to example app and check the logs.

Repair error logging

---

android/gradle/wrapper/gradle-wrapper.properties

Bug fix
Plugin restricts consuming applications to use gradle-wrapper version 4.10.1. 
Plugin should no longer be restricted to a specific gradle wrapper version.
No
Create a new Flutter App and make sure you use a gradle version bigger then 4.10.1 (e.g. 5.1.1), take a reference to the `permission_handler` plugin in you pubspec.yaml file and try to compile the Android application: `flutter build apk`
#136

Removed redundant gradle wrapper

---

ios/Classes/PermissionManager.h
ios/Classes/PermissionManager.m
ios/Classes/strategies/StoragePermissionStrategy.h
ios/Classes/strategies/StoragePermissionStrategy.m
lib/src/permission_enums.dart

Adds the missing `StoragePermissionStrategy` for iOS only. For example, it is needed to store files in the `Documents` folder. Without this stategy permission is currently denied on request.
Permission is denied on request.  
Special permission on writing into directories like `Documents` or `Downloads` isn't required since every app runs in its own sandbox. Permission is implicitly granted.
Permission is automatically granted on request.
No
No
None

Adds support for StoragePermissionStrategy on iOS

---

android/src/main/java/com/baseflow/permissionhandler/PermissionHandlerPlugin.java
example/android/app/src/main/AndroidManifest.xml

Bug fix
When compiling against API 29 a the compiler warns / fails because the permission `PROCESS_OUTGOING_CALLS` have been deprecated by Google.
Instead of requesting the `PROCESS_OUTGOING_CALLS ` permissions, the plugin is now requesting the `BIND_CALL_REDIRECTION_SERVICE` permission as suggested by [Google here](https://developer.android.com/reference/android/Manifest.permission.html#PROCESS_OUTGOING_CALLS).
Yes. This code will not compile when running against a target API below 29.
Run the example test/
- fixes #167

Fixed deprecated permissions

---

android/src/main/java/com/baseflow/permissionhandler/PermissionHandlerPlugin.java
example/android/app/src/debug/AndroidManifest.xml
example/android/app/src/main/AndroidManifest.xml
example/lib/main.dart
ios/Classes/PermissionHandlerEnums.h
lib/src/permission_enums.dart

Feature
New scoped storage in Android 10 restricts access to media location. In order to get permission to read it, app should request `ACCESS_MEDIA_LOCATION`.
We now have a new permission that framework can handle: `ACCESS_MEDIA_LOCATION` (Android only). This permission introduced a new enum value on `PermissionGroup` named `access_media_location`
No, unless anyone was relying on `PermissionGroup.unknown = 17`. Now it is 18 on the enum.
In Android, ask for permission `access_media_location`. After granting that permission you should be able to read GPS information from image
None

Added ACCESS_MEDIA_LOCATION permission handling for Android >= 10

---

android/build.gradle
example/android/build.gradle
example/android/gradle/wrapper/gradle-wrapper.properties

Feature
Currently the used versions of the Grable Plugin and Gradle Wrapper are out of sync with the stable version of Flutter.
Bring the Gradle plugin and Gradle wrapper versions in sync with Flutter stable (1.12.13+hotfix.5).
No
Compile and run the example project
#173

Align versions of Gradle with current stable version of Flutter

---

README.md
android/src/main/java/com/baseflow/permissionhandler/PermissionHandlerPlugin.java
android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java
lib/src/permission_enums.dart

Added new permission state on android devices when user denied permission request with selected checkbox "Never ask again"
When user "Never ask again" it returns  status of  permission "denied", so we can't understand actual state of permission and after permission request we got nothing 
When user "Never ask again" it returns new permission status neverAskAgain
https://github.com/Baseflow/flutter-permission-handler/issues/96

Added neverAskAgain permission status for android devices

---

android/src/main/java/com/baseflow/permissionhandler/PermissionHandlerPlugin.java

Fixes several warnings
Android Studio is warning that some statements are only supported on certain SDK versions of Android.
Added checks to ensure code is executed only when supported.
No

Fix several warnings

---

android/src/main/java/com/baseflow/permissionhandler/PermissionHandlerPlugin.java

Bug fix
```updatePermissionShouldShowStatus``` calls before detect it status so we got ```PermissionStatus.neverAskAgain``` when we have asked  permission fist time
```PermissionStatus.neverAskAgain``` returns only when user checks neverAskAgain

Moved updating showing permission status after detecting it status

---

android/src/main/java/com/baseflow/permissionhandler/PermissionHandlerPlugin.java
lib/src/permission_enums.dart

Feature - New permission for Android Q Activity Recognition, which is dangerous on Android Q and above
Unable to request permissions for Activity Recognition API when targeting Android Q / 29
Support for ACTIVITY_RECOGNITION permission
No
https://developer.android.com/about/versions/10/privacy/changes#physical-activity-recognition

Add Android Q Activity Recognition support

---

permission_handler/android/src/main/java/com/baseflow/permissionhandler/MethodCallHandlerImpl.java
permission_handler/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java
permission_handler/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java
permission_handler/android/src/main/java/com/baseflow/permissionhandler/ServiceManager.java

Bug fix (Android only)
Currently the `checkPermissionStatus` requires an activity as context which results in an error when an App is running isolated (or as a background service). 
The new behavior is that the plugin will use the ApplicationContext to check the permission status. It will only use the `Activity` to try to determine if permissions are denied and should not be asked again (using `shouldShowRequestPermissionRationale`). In case the `Activity` is not available this check will be skipped. This means that in cases where the App is running isolated the permissions can either be `granted` or `denied` and you will not be informed about the never ask again state.
No
-
Solves #233

Fallback on application context if activity is null

---

permission_handler/ios/Classes/strategies/NotificationPermissionStrategy.m

Bug fix
In case of iOS 10+ the call to grant permission was made outside of the `requestAuthorizationWithOptions(..)` block and returned immediately always with `PermissionStatusGranted`, which leads to a totally useless permission request.
This fix moves the call to the correct place - inside of `requestAuthorizationWithOptions(..)`'s block.
No.

iOS NotificationPermissionStrategy: Fixes wrong completionHandler call

---

permission_handler/ios/Classes/strategies/NotificationPermissionStrategy.m

Bug fix
Unfortunately, my last fix introduced a new bug! The call for `[[UIApplication sharedApplication] registerForRemoteNotifications]` **MUST** be handled on main thread! It wasn't.
It's called on main thread now.
No.
n/a
n/a

Fixes the fix of wrong completionHandler call

---

permission_handler/ios/Classes/strategies/LocationPermissionStrategy.m

Bug fix (back porting fix done in https://github.com/Baseflow/flutter-permission-plugins/pull/25 to permission-handler)
kCLAuthorizationStatusAuthorizedWhenInUse was returning PermissionStatusDenied
kCLAuthorizationStatusAuthorizedWhenInUse is now returning PermissionStatusGranted
No
https://github.com/Baseflow/flutter-permission-plugins/pull/25

kCLAuthorizationStatusAuthorizedWhenInUse was returning PermissionStatusDenied

---

permission_handler/lib/permission_handler.dart

Bug fix.
Missing export for PermissionWithService, which prevents clients from consuming it.

export PermissionWithService

---

permission_handler/ios/Classes/PermissionManager.m

Should fix issue #202 . 
Deprecated ([see doc](https://developer.apple.com/documentation/foundation/nsvalue/1415141-getvalue?language=objc)) call for getValue is being used.
Replaced deprecated call with typecast.
No
Issue #202 
[Apple documentation](https://developer.apple.com/documentation/foundation/nsvalue/1415141-getvalue?language=objc)

iOS: Replace the deprecated getValue call with a simple typecast

---

permission_handler/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java

It fixes a bug on Android Q+ when READ_PHONE_NUMBERS permission is needed but is not granted immediately with Permission.phone.request()
More info: https://developer.android.com/about/versions/11/privacy/permissions#phone-numbers
READ_PHONE_NUMBERS permission is not granted after Permission.phone.request()
No

adding READ_PHONE_NUMBERS permission to PHONE group

---

permission_handler/android/src/main/java/com/baseflow/permissionhandler/PermissionConstants.java
permission_handler/example/lib/plugin_example/permission_widget.dart
permission_handler/ios/Classes/PermissionHandlerEnums.h
permission_handler/ios/Classes/PermissionManager.m
permission_handler/ios/Classes/strategies/PhotoPermissionStrategy.h
permission_handler/ios/Classes/strategies/PhotoPermissionStrategy.m
permission_handler/lib/permission_handler.dart
permission_handler/pubspec.yaml
permission_handler_platform_interface/lib/src/permission_status.dart
permission_handler_platform_interface/lib/src/permissions.dart
permission_handler_platform_interface/pubspec.yaml

photos permission supported for iOS 14+
the permission status "limited" is not returned at this moment
No
check if all the permissions still work with this change

iOS 14 update for photos permission

---

permission_handler_platform_interface/CHANGELOG.md
permission_handler_platform_interface/lib/src/permission_status.dart
permission_handler_platform_interface/pubspec.yaml

PermissionStatus.undetermined has been removes in favor of PermissionStatus.denied. 
PermissionStatus.undetermined is returned
PermissionStatus.undetermined doesn't exist
Yes

Removed PermissionStatus.undetermined

---

README.md
permission_handler/CHANGELOG.md
permission_handler/android/src/main/java/com/baseflow/permissionhandler/PermissionConstants.java
permission_handler/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java
permission_handler/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java
permission_handler/android/src/main/java/com/baseflow/permissionhandler/ServiceManager.java
permission_handler/example/android/app/src/main/AndroidManifest.xml
permission_handler/ios/Classes/PermissionHandlerEnums.h
permission_handler/ios/Classes/PermissionManager.h
permission_handler/ios/Classes/PermissionManager.m
permission_handler/ios/Classes/strategies/BluetoothPermissionStrategy.h
permission_handler/ios/Classes/strategies/BluetoothPermissionStrategy.m
permission_handler/pubspec.yaml
permission_handler_platform_interface/CHANGELOG.md
permission_handler_platform_interface/lib/src/permissions.dart
permission_handler_platform_interface/pubspec.yaml

Feature
Currently it is not possible to ask for bluetooth permissions on iOS. This is introduced in iOS 13. This permission is not needed on Android and will always return 'granted'.
Implement Bluetooth permission.
The request for permission is a bit different as that is automatically done while doing a bluetooth action.
No
I still have to verify if this really works with Bluetooth denied, but I have to use it with some bluetooth calls, which aren't available in the example.
https://medium.com/flawless-app-stories/handling-ios-13-bluetooth-permissions-26c6a8cbb816

Add bluetooth permission.

---

permission_handler/CHANGELOG.md
permission_handler/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java
permission_handler/pubspec.yaml

Bug fix
On pre Android Q devices, permission for `ACCESS_ACTIVITY_RECOGNITION` and `ACCESS_MEDIA_LOCATION` are always return as denied. This is incorrect as permissions are implicitly granted on earlier devices.
Permissions will now be returned as granted as expected.
No
Simply run the example App on pre Android Q device or emulator and check permissions for the "ActivityRecognition" and "MediaLocation" permissions.
N/A (added some additional comments in code to explain certain cases).

Correctly handle some permissions on pre Android Q

---

permission_handler_platform_interface/lib/permission_handler_platform_interface.dart
permission_handler_platform_interface/lib/src/permissions.dart

This change implements the equality operator for `Permisson` class.
I added `@immutable` annotation to `Permission` according to enabled lint rule [avoid_equals_and_hash_code_on_mutable_classes](https://dart-lang.github.io/linter/lints/avoid_equals_and_hash_code_on_mutable_classes.html).<br>The class is already not mutable, this annotation was added to satisfy linter.
`Permission` equals another `Permission` only if they are the same instance.
`Permission` equals another `Permission` when they have equal `Permission.value`.
Yes. If someone extends `Permission` class and the child class is not immutable, they'll get a warning message.
I'd like to write tests for equality, but tests directory is missing from `develop` branch.

Implement the equality operator for Permission class

---

permission_handler_platform_interface/CHANGELOG.md
permission_handler_platform_interface/lib/src/permissions.dart
permission_handler_platform_interface/pubspec.yaml
permission_handler_platform_interface/test/src/permissions_test.dart

This change implements the equality operator for `Permisson` class.
I added `@immutable` annotation to `Permission` according to enabled lint rule [avoid_equals_and_hash_code_on_mutable_classes](https://dart-lang.github.io/linter/lints/avoid_equals_and_hash_code_on_mutable_classes.html).<br>The class is already not mutable, this annotation was added to satisfy linter.
`Permission` equals another `Permission` only if they are the same instance.
`Permission` equals another `Permission` when they have equal `Permission.value`.
Yes. If someone extends `Permission` class and the child class is not immutable, they'll get a warning message.
Added additional unit tests to proof that the equality operator is working.

Implement equality for Permission

---

permission_handler/example/lib/plugin_example/permission_list.dart

Updated example app, showing the right permissions for the right platform
Shows some permissions for the wrong platform
shows the right permission for the right platform
No

Updated example app

---

permission_handler/CHANGELOG.md
permission_handler/pubspec.yaml

Bug fix
Two instances of the permission class can not be compared.
Implemented the equality operator.
No

Upgrade to permission_handler_platform_interface 3.1.3

---

permission_handler_platform_interface/CHANGELOG.md
permission_handler_platform_interface/lib/src/permissions.dart
permission_handler_platform_interface/pubspec.yaml
permission_handler_platform_interface/test/src/permissions_test.dart

Introduces the 'Manage External Storage' permission
No

Added manage external storage permission

---

permission_handler/CHANGELOG.md
permission_handler/android/build.gradle
permission_handler/android/src/main/java/com/baseflow/permissionhandler/MethodCallHandlerImpl.java
permission_handler/android/src/main/java/com/baseflow/permissionhandler/PermissionConstants.java
permission_handler/android/src/main/java/com/baseflow/permissionhandler/PermissionHandlerPlugin.java
permission_handler/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java
permission_handler/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java
permission_handler/example/android/app/build.gradle
permission_handler/example/android/app/src/main/AndroidManifest.xml
permission_handler/example/lib/plugin_example/permission_list.dart
permission_handler/ios/Classes/PermissionHandlerEnums.h
permission_handler/pubspec.yaml

1. Registered listeners on the plugin level to prevent memory leaks or unwanted behaviour
2. Added MANAGE_EXTERNAL_STORAGE permissions for Android 11 and higher
When requesting a permission multiple times during the live time of the App there will be multiple listeners in memory and all will be fired each time an activity result comes in
The listeners get registered on the plugin level so there will not be multiple listeners put in memory when requesting multiple permissions.
Also added the MANAGE_EXTERNAL_STORAGE permission for Android 11 and up.
Yes, build.gradle needed to be updated, compile SDK version is now set to 30 in the build.gradle for handling the MANAGE_EXTERNAL_STORAGE permission
Listeners bug mentioned in #389 will be solved
Added MANAGE_EXTERNAL_STORAGE as requested in …

Added MANAGE_EXTERNAL_STORAGE permission

---

permission_handler_platform_interface/CHANGELOG.md
permission_handler_platform_interface/lib/src/permissions.dart
permission_handler_platform_interface/pubspec.yaml
permission_handler_platform_interface/test/src/permissions_test.dart

Added SYSTEM_ALERT_WINDOW permission
No
Android's documentation about the [SYSTEM_ALERT_WINDOW](https://developer.android.com/reference/android/Manifest.permission#SYSTEM_ALERT_WINDOW)

Added support for SYSTEM_ALERT_WINDOW permission

---

README.md

doc update for 7.x version's min compile SDK version on Android
minCompileSdk 28
minCompileSdk 30
No

Doc: update android min compile sdk to 30 for 7.x

---

permission_handler/CHANGELOG.md
permission_handler/android/src/main/java/com/baseflow/permissionhandler/MethodCallHandlerImpl.java
permission_handler/android/src/main/java/com/baseflow/permissionhandler/PermissionConstants.java
permission_handler/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java
permission_handler/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java
permission_handler/example/android/app/src/main/AndroidManifest.xml
permission_handler/ios/Classes/PermissionHandlerEnums.h
permission_handler/pubspec.yaml

Added the 'SYSTEM_ALERT_WINDOW' in the permission_handler
User can ask for the 'SYSTEM_ALERT_WINDOW' permission now
No

Added 'SYSTEM_ALERT_WINDOW' permission

---

permission_handler/README.md

docs (README.md)
[Issue](https://github.com/Baseflow/flutter-permission-handler/issues/541#issuecomment-830564097)
Permission Handler for android requires compileSdkVersion 30

docs: compileSdkVersion 28 to 30

---

permission_handler_platform_interface/CHANGELOG.md
permission_handler_platform_interface/lib/src/permissions.dart
permission_handler_platform_interface/pubspec.yaml
permission_handler_platform_interface/test/src/permissions_test.dart

Added appTrackingTransparency permission for iOS
Added appTrackingTransparency permission for iOS
No
issue #375

Added appTrackingTransparency permission

---

permission_handler/CHANGELOG.md
permission_handler/README.md
permission_handler/example/ios/Podfile
permission_handler/pubspec.yaml

docs update.
`Podfile` link at https://pub.dev/packages/permission_handler/changelog#800 is broken.
Fix the link.
No.
No.
- https://pub.dev/packages/permission_handler/changelog#800

Fix broken Podfile link

---

permission_handler_platform_interface/CHANGELOG.md
permission_handler_platform_interface/lib/src/permission_status.dart
permission_handler_platform_interface/pubspec.yaml

Documentation update
Current documentation suggests the `PermissionStatus.permanentlyDenied` status is only used on Android.
Since version 6.0.0 the `PermissionStatus.permanentlyDenied` status is used on all platforms and the documentation should reflect this.
No
n/a
- #574

Update API doc on permanentlyDenied status

---

permission_handler_platform_interface/CHANGELOG.md
permission_handler_platform_interface/lib/src/permissions.dart
permission_handler_platform_interface/pubspec.yaml
permission_handler_platform_interface/test/src/permissions_test.dart

- Add critical alerts for iOS 
- Add AccessNotificationPolicy on Android
Nope
Run on Android and test notification policy — iOS see video in other PR

Add criticalAlerts for iOS and accessNotificationPolicy for Android

---

permission_handler/CHANGELOG.md
permission_handler/ios/Classes/PermissionManager.m
permission_handler/ios/Classes/strategies/ContactPermissionStrategy.m
permission_handler/pubspec.yaml

Bug fix
In some situations users of the plugin run into issues where they cannot compile their App when using the permission_handler plugin due to deprecation warnings. Even though the permission_handler plugin correctly uses the `@available` attribute to run the correct code on the right iOS version/ 
Added additional lines to ignore deprecation warnings when for code that is specifically available to support older iOS versions.
No
-
- Fixes #607

Ignore deprecation warnings for code that targets older iOS versions

---

permission_handler_platform_interface/lib/src/permission_status.dart

Some users (me included) were puzzled when `isPermanentlyDenied` returned `false` even when permission was permanently denied.

Explain isPermanentlyDenied

---

permission_handler/CHANGELOG.md
permission_handler/ios/Classes/strategies/ContactPermissionStrategy.m
permission_handler/ios/Classes/strategies/LocationPermissionStrategy.m
permission_handler/pubspec.yaml

Hotfix bug where requesting location after being granted would result into a memory error.
No
Issue #633

Hotfix - requesting location after being granted results in memory error

---

permission_handler/CHANGELOG.md
permission_handler/ios/Classes/PermissionManager.m
permission_handler/pubspec.yaml

Bug fix
When requesting permissions on iOS 12 or below the permission_handler will crash and reports an EXC_BAD_ACCESS exception. Caused by a block callback function that is removed once a related class was set to `nil`.
In this case we can call the block before we nullify the related class. I included a comment to describe the importance of the calling order. Note that this bug was also resolved in the Objective-C runtime that ships with iOS 13 and higher.
No
- Fixes #638

Fixed memory reference error on iOS 12 and below.

---

permission_handler/CHANGELOG.md
permission_handler/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java
permission_handler/pubspec.yaml

Bug fix
Currently, when opening the Location Settings and changing location settings and thus permissions, the app will crash when returning to the application. This only occurs in release mode. When running the application in development mode, the application will 'freeze' instead of crash.
In release mode the nullpointerexception will no longer occur. In development mode, the app will still freeze when returning from the Location Settings intent. 
No
Use the example application
Does not apply

Permission Manager / Location Settings intent nullpointer fix

---

permission_handler_platform_interface/CHANGELOG.md
permission_handler_platform_interface/analysis_options.yaml
permission_handler_platform_interface/lib/src/method_channel/method_channel_permission_handler.dart
permission_handler_platform_interface/lib/src/method_channel/utils/codec.dart
permission_handler_platform_interface/lib/src/permission_status.dart
permission_handler_platform_interface/lib/src/permissions.dart
permission_handler_platform_interface/lib/src/service_status.dart
permission_handler_platform_interface/pubspec.yaml
permission_handler_platform_interface/test/src/method_channel/method_channel_mock.dart
permission_handler_platform_interface/test/src/method_channel/utils/coded_test.dart
permission_handler_platform_interface/test/src/permission_handler_platform_interface_test.dart
permission_handler_platform_interface/test/src/permission_status_test.dart
permission_handler_platform_interface/test/src/permissions_test.dart
permission_handler_platform_interface/test/src/service_status_test.dart

Bug fix
Unit tests fail when running on latest stable of Flutter because the `setMockMethodChannel` method has been moved from the `MethodChannel` class to the `TestDefaultBinaryMessengerBinding.instance!.defaultBinaryMessenger` class.
Migrate the implementation of the `MethodChannelMock` class to use the new `TestDefaultBinaryMessengerBinding.instance!.defaultBinaryMessenger` to register a mock handler, instead of the `MethodChannel` class.
No
Unit tests should succeed in tree.

Update the MethodChannelMock due to breaking changes.

---

permission_handler/pubspec.yaml

Updates the permission_handler (app facing package) to use the latest version of the permission_handler_platform_interface package.

Update to latest version of platform_interface

---

permission_handler/CHANGELOG.md
permission_handler/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java
permission_handler/example/pubspec.yaml
permission_handler/pubspec.yaml

Bug fix
When checking permissions on pre Android M (without support for runtime permissions) the result is always `PermissionStatus.denied` while `PermissionStatus.granted` is the expected value.
Return `PermissionStatus.granted` on pre Android M devices when permissions are not specified in the `AndroidManifest.xml` file.
No

Ensure checking permissions on pre Android M works correctly.

---

permission_handler/CHANGELOG.md
permission_handler/README.md
permission_handler/pubspec.yaml

Update instructions on configuring the Android `compileSdkVersion` to value `31` as required by version 8.2.0 of the permission_handler.

Update compileSdkVersion documentation.

---

permission_handler/CHANGELOG.md
permission_handler/ios/Classes/PermissionManager.m
permission_handler/ios/Classes/strategies/BluetoothPermissionStrategy.h
permission_handler/ios/Classes/strategies/BluetoothPermissionStrategy.m
permission_handler/pubspec.yaml

Fixes problem that request Ble as soon as the app started  https://github.com/Baseflow/flutter-permission-handler/issues/591
As soon as you open the app the Bluetooth permission is requested if 'PERMISSION_BLUETOOTH=1',
Request bluetooth connection only when serviceStatus or requestPermission is called
Yes! Devs could have consider this while implementing the permission flow throw their app
https://github.com/Baseflow/flutter-permission-handler/issues/591
https://user-images.githubusercontent.com/19904063/143449302-8d34f925-340e-42b5-80cc-437bff8f17ff.MP4

fix: init CBCentralManager lazely

---

permission_handler/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java

Bug fix
android Q  locationAlways Permission request not show toash
fix android Q  locationAlways Permission 
no
android Q  phone click locationAlways Permission request

android Q  locationAlways Permission not show toash

---

permission_handler/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java

Bug fix
the WRITE_EXTERNAL_STORAGE permission may not request on Android Q or higher which configuring targetSDK <=29 and externalStorageLegacy = true
fixed the problem
no
run on Android Q or higher which configuring targetSDK <=29 and externalStorageLegacy = true, request WRITE_EXTERNAL_STORAGE permission
- [x ] I made sure all projects build.
- [x ] I rebased onto current `master`.

Fixed the WRITE_EXTERNAL_STORAGE permission may not request on AndroidQ

---

permission_handler_apple/AUTHORS
permission_handler_apple/CHANGELOG.md
permission_handler_apple/ios/Classes/strategies/LocationPermissionStrategy.h
permission_handler_apple/ios/Classes/strategies/LocationPermissionStrategy.m
permission_handler_apple/pubspec.yaml

Bug fix
I will apologise right now for the long explanation, but I think it is warranted to understand the complicated nature of the issue and how it was fixed.
TLDR; When you request `locationAlways` and deny the request, then the next permission request results in a `ERROR_ALREADY_REQUESTING_PERMISSIONS` error. This is due odd behaviour in the iOS API and a callback that never gets called.
Longer explanation:
The error occurs when we try to obtain `locationAlways` permission. For this, we first have to obtain `locationWhenInUse` permission, and then upgrade our permission by requesting `locationAlways`. The way this is done natively is by calling the asynchronous `requestWhenInUseAuthorization` and `requestAlwaysAuthorization` respectively. …

Fix ERROR_ALREADY_REQUESTING_PERMISSIONS on iOS after requesting locationAlways

---

permission_handler/example/android/.settings/org.eclipse.buildship.core.prefs
permission_handler_android/CHANGELOG.md
permission_handler_android/android/.classpath
permission_handler_android/android/.settings/org.eclipse.buildship.core.prefs
permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java
permission_handler_android/example/android/.settings/org.eclipse.buildship.core.prefs
permission_handler_android/pubspec.yaml

Bug fix
The WRITE_EXTERNAL_STORAGE permission is requested based on the Android target SDK instead of the actual SDK that the device is working with.
Corrected this mistake introduced in PR #765 
No
#765

Revert PR 765

---

.github/workflows/permission_handler.yaml
.github/workflows/permission_handler_android.yaml
.github/workflows/permission_handler_apple.yaml
.github/workflows/permission_handler_platform_interface.yaml

Maintenance
The GitHub Actions steps "checkout" and "flutter-action" are outdated and cause failures downloading flutter dependencies.
Updated the GitHub Actions steps to the latest versions (checkout to v3 and flutter-action to v2 respectively).
No

Updated GitHub workflow actions

---

permission_handler/example/pubspec.yaml
permission_handler_android/example/pubspec.yaml
permission_handler_apple/example/pubspec.yaml
permission_handler_windows/example/pubspec.yaml

Bug fix
Error when running the example projects, caused by faulty pubspec.yaml configurations
No errors when running example projects.
No
Run the example projects.
-

Updated pubspec.yaml files config for baseflow_plugin_template

---

permission_handler_platform_interface/test/src/permission_handler_platform_interface_test.dart

Currently, in some circumstances where a subclasses of
`PlatformInterface` erroneously uses `implements` rather than
`extends`, a `NoSuchMethodError` will be thrown (in spite of the
documentation at
https://pub.dev/documentation/plugin_platform_interface/latest/plugin_platform_interface/PlatformInterface/verify.html
claiming that `AssertionError` will be thrown).
After https://github.com/flutter/flutter/issues/109339 is fixed, the
correct type of exception will be thrown.  To avoid a test breakage in
`geolocator_platform_interface_test.dart` when the fix happens, we
need to modify the test so that it doesn't care what kind of exception
is thrown.
Bug fix
The test expects `NoSuchMethodError` to be thrown; this will break after https://github.com/flutter/flutter/issues/109339 is fixed.
The …

Prepare for issue flutter/flutter#109339

---

permission_handler_platform_interface/lib/src/permission_status.dart

Updated `permission_handler_platform_interface\lib\src\permission_status.dart` comments to better reflect current funtionality
Docs update
-
-
No
-
[Issue 826](https://github.com/Baseflow/flutter-permission-handler/issues/826)
- [-] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy](https://dart.dev/tools/pub/versioning).
- [-] I updated CHANGELOG.md to add a description of the change.

Updated permission_status.dart comments

---

permission_handler_platform_interface/CHANGELOG.md
permission_handler_platform_interface/pubspec.yaml

`permission_handler_platform_interface` version update for [these](https://github.com/Baseflow/flutter-permission-handler/pull/914) documentation changes.
-
-
No
-
[826](https://github.com/Baseflow/flutter-permission-handler/issues/826)

Updated CHANGELOG.md and pubspec.yaml within the platform_interface

---

permission_handler/CHANGELOG.md
permission_handler/README.md
permission_handler/pubspec.yaml

- Fix README
- https://github.com/Baseflow/flutter-permission-handler/blob/master/permission_handler/ios/Classes/PermissionHandlerEnums.h is missing
- https://github.com/Baseflow/flutter-permission-handler/blob/master/permission_handler_apple/ios/Classes/PermissionHandlerEnums.h is correct
- No

Fix PermissionHandlerEnums link

---

permission_handler/CHANGELOG.md
permission_handler/pubspec.yaml

With this PR, the right section on pub.dev will show the View/report issues link to GitHub again, like [here](https://pub.dev/packages/android_id) (the show-logic was recently changed).
It shows a `Homepage` link
It shows links to `Repository (GitHub)` and `View/report issues`
No.

Update links for pub.dev

---

permission_handler_platform_interface/CHANGELOG.md
permission_handler_platform_interface/lib/src/permissions.dart
permission_handler_platform_interface/pubspec.yaml
permission_handler_platform_interface/test/src/permissions_test.dart

Added support for new Android 13 permission: NEARBY_WIFI_DEVICES in the platform interface package
No support for this permission
Support for this permission
No
-
[859](https://github.com/Baseflow/flutter-permission-handler/issues/859)

Added platform interface support for Android 13: NEARBY_WIFI_DEVICES

---

permission_handler/CHANGELOG.md
permission_handler/example/android/app/src/main/AndroidManifest.xml
permission_handler/pubspec.yaml

Feature: added support for new Android 13 NEARBY_WIFI_DEVICES permission
No support
Support added
No
-
[PR: 927](https://github.com/Baseflow/flutter-permission-handler/pull/927)
[ISSUE: 859](https://github.com/Baseflow/flutter-permission-handler/issues/859)

Added support for new Android 13 NEARBY_WIFI_DEVICES permission

---

permission_handler_platform_interface/CHANGELOG.md
permission_handler_platform_interface/lib/src/permissions.dart
permission_handler_platform_interface/pubspec.yaml
permission_handler_platform_interface/test/src/permissions_test.dart

Added support for the new Android 13 permissions: SCHEDULE_EXACT_ALARM, READ_MEDIA_IMAGES, READ_MEDIA_VIDEO and READ_MEDIA_AUDIO
No support
Permissions supported
No
-
[859](https://github.com/Baseflow/flutter-permission-handler/issues/859)

Added support for new Android media and alarm permissions

---

permission_handler_android/CHANGELOG.md
permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionConstants.java
permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java
permission_handler_android/example/android/app/src/main/AndroidManifest.xml
permission_handler_android/pubspec.yaml
permission_handler_apple/CHANGELOG.md
permission_handler_apple/ios/Classes/PermissionHandlerEnums.h
permission_handler_apple/pubspec.yaml
permission_handler_windows/CHANGELOG.md
permission_handler_windows/pubspec.yaml
permission_handler_windows/windows/permission_constants.h

Added support in the android platform package for the new Android 13 permissions: SCHEDULE_EXACT_ALARM, READ_MEDIA_IMAGES, READ_MEDIA_VIDEO and READ_MEDIA_AUDIO
No support
Permissions supported
No
-
[859](https://github.com/Baseflow/flutter-permission-handler/issues/859)

Added platform support for new android granular media and alarm permissions

---

permission_handler_android/CHANGELOG.md
permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java
permission_handler_android/pubspec.yaml

Bug fix
Plugin always returns `granted` for `SCHEDULE_EXACT_ALARM` permission on Android 12 and 13 even if user revokes the permission in app settings.
Plugin checks status of `SCHEDULE_EXACT_ALARM` properly as it is recommended in https://developer.android.com/about/versions/14/changes/schedule-exact-alarms
No
Try to run current version of the plugin on Android 12 or 13 and revoke alarm permission. Note, this particular permission is not in `Permissions` section, but is a separate menu item in `App info`:
There is a bug report about this issue already: https://github.com/Baseflow/flutter-permission-handler/issues/987
Official documentation: https://developer.android.com/about/versions/14/changes/schedule-exact-alarms

Fix exact alarm permission status check on Android

---

permission_handler_platform_interface/CHANGELOG.md
permission_handler_platform_interface/lib/src/permissions.dart
permission_handler_platform_interface/pubspec.yaml
permission_handler_platform_interface/test/src/permissions_test.dart

Separates the changes in the "permission_handler_platform_interface" package from the larger #1065 PR.
Relates to issue #1019

Adds BODY_SENSORS_BACKGROUND support

---

permission_handler_platform_interface/CHANGELOG.md
permission_handler_platform_interface/lib/src/permissions.dart
permission_handler_platform_interface/pubspec.yaml

Fixes misalignment in the `Permission` enum after adding the new BODY_SENSORS_BACKGROUND permission.

Fixes misalignment with BODY_SENSORS_BACKGROUND

---

permission_handler/CHANGELOG.md
permission_handler/example/android/app/src/main/AndroidManifest.xml
permission_handler/pubspec.yaml

This PR updates the documentation of the Android Manifest of the example app, adding to the explanation of the `READ_EXTERNAL_STORAGE`, `READ_MEDIA_IMAGES`, `READ_MEDIA_VIDEO` and `READ_MEDIA_AUDIO` permissions. It aims to give a bit more context to the [changes in Android 13](https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions). This file is references in the README, and probably a common-seen file for users of the plugin.
Closes #955, #1026, #1066.

Mention use of granular media permissions in AndroidManifest

---

permission_handler_apple/CHANGELOG.md
permission_handler_apple/example/ios/Flutter/AppFrameworkInfo.plist
permission_handler_apple/example/ios/Podfile
permission_handler_apple/example/ios/Runner.xcodeproj/project.pbxproj
permission_handler_apple/example/ios/Runner/Info.plist
permission_handler_apple/ios/Classes/strategies/LocationPermissionStrategy.m
permission_handler_apple/pubspec.yaml

The application will hang on the `Permission.locationAlways` future when requesting location always permissions directly after the user has granted "Allow once" permission.
This PR will fix this issue and makes sure the `PermissionStatus.denied` status is returned in these cases.
- Fixes #802
- Fixes #1011
- Fixes #1018

Fixes hang when requesting location always permission.

---

.github/workflows/no-response.yaml

Replaces the `no-response` bot with a more advanced version. The main reason for this change is to make sure the bot also removes the `status: needs more info` label when other contributors post an update. 
The old bot only removed the label if the original poster responded, this might lead in issues being closed while sufficient information was provided.
[Contributor Guide]: https://github.com/Baseflow/flutter-geolocator/blob/master/CONTRIBUTING.md

Replace the stale both with more advanced version

---

permission_handler_apple/CHANGELOG.md
permission_handler_apple/ios/Classes/strategies/LocationPermissionStrategy.m
permission_handler_apple/pubspec.yaml

In a previous update to the plugin, we return `PermissionStatusDenied` when the location status is `Undetermined`. This is not correct however, as this status is emitted by iOS when the permission dialog is opened. This leads to a bug where the permission status returned by Dart is always `PermissionStatus.denied`, regardless of the response of the user.
Closes #1086

Remove callback on undetermined location status

---

permission_handler/CHANGELOG.md
permission_handler/README.md
permission_handler/pubspec.yaml
permission_handler_platform_interface/CHANGELOG.md
permission_handler_platform_interface/lib/src/permissions.dart
permission_handler_platform_interface/pubspec.yaml

This PR adds an FAQ section to the README.md of the permission_handler package, providing more details on using the `Permission.storage` permission on Android.
It also includes updated Dart docs on the `Permission.storage` enum defined in the permission_handler_platform_interface package.
Resolves #1085

Updates documentation on using the "Permission.storage"

---

permission_handler_android/CHANGELOG.md
permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/ServiceManager.java
permission_handler_android/pubspec.yaml

Fixes #1094.
Currently if the status of Bluetooth service is checked (see https://github.com/Baseflow/flutter-permission-handler/issues/773, and my comment for how I currently do it), an exception is thrown:
```
Launching lib/main.dart on Nexus 5 in debug mode...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:50209/4CUXZdFqgsA=/ws
E/MethodChannel#flutter.baseflow.com/permissions/methods(17691): Failed to handle method call
E/MethodChannel#flutter.baseflow.com/permissions/methods(17691): java.lang.IllegalStateException: Reply already submitted
E/MethodChannel#flutter.baseflow.com/permissions/methods(17691): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:435) …
```

Fix double 'onSuccess' call when checking BT service status

---

permission_handler_apple/CHANGELOG.md
permission_handler_apple/example/lib/main.dart
permission_handler_apple/ios/Classes/PermissionManager.m
permission_handler_apple/ios/Classes/strategies/AppTrackingTransparencyPermissionStrategy.m
permission_handler_apple/ios/Classes/strategies/AudioVideoPermissionStrategy.m
permission_handler_apple/ios/Classes/strategies/BluetoothPermissionStrategy.m
permission_handler_apple/ios/Classes/strategies/ContactPermissionStrategy.m
permission_handler_apple/ios/Classes/strategies/CriticalAlertsPermissionStrategy.m
permission_handler_apple/ios/Classes/strategies/EventPermissionStrategy.m
permission_handler_apple/ios/Classes/strategies/LocationPermissionStrategy.m
permission_handler_apple/ios/Classes/strategies/MediaLibraryPermissionStrategy.m
permission_handler_apple/ios/Classes/strategies/NotificationPermissionStrategy.m
permission_handler_apple/ios/Classes/strategies/PermissionStrategy.h
permission_handler_apple/ios/Classes/strategies/PhonePermissionStrategy.m
permission_handler_apple/ios/Classes/strategies/PhotoPermissionStrategy.m
permission_handler_apple/ios/Classes/strategies/SensorPermissionStrategy.m
permission_handler_apple/ios/Classes/strategies/SpeechPermissionStrategy.m
permission_handler_apple/ios/Classes/strategies/StoragePermissionStrategy.m
permission_handler_apple/ios/Classes/strategies/UnknownPermissionStrategy.m
permission_handler_apple/pubspec.yaml

This PR updates the Apple implementation, fixing an issue where the Bluetooth service status was never resolved properly. To this end it
- Makes `checkServiceStatus` async
- Keeps track of `PermissionStrategy` in `PermissionManager` (hold the reference to guarantee that the callback fires)
Additionally, it updates the displayed permission in the example app, as these were out of sync with the newest permissions.
This PR is part of feature #773.

Allow querying Bluetooth service status on iOS (Apple)

---

permission_handler_android/CHANGELOG.md
permission_handler_android/android/build.gradle
permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java
permission_handler_android/example/android/build.gradle
permission_handler_android/pubspec.yaml

Currently the `permission_handler_android` package adds the `"-Xlint:deprecation","-Xlint:unchecked","-Werror"` build arguments which ensure that the Java compiler throws an error if the code contains "deprecation" or "unchecked" warnings.
Unfortunately the arguments are added in the `android/build.gradle` file which result that the arguments are populated all the through to the consuming app. This means if the consuming app (or other plugins used by the consuming app) contains "deprecation" or "unchecked" warnings the app will not compile. While this might be good practice, developers should be allowed to make their own choice and this should not be enforced upon them by the permission_handler plugin.
This PR will move the use of the compiler argument to the example app which will no …

Moves Java compile arguments

---

permission_handler_platform_interface/lib/src/permissions.dart

fix typo in word the 'deprecated'
- fix type
- [done] I made sure the project builds.
- [done] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [done] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is does not need version changes.
- [done] I updated `CHANGELOG.md` to add a description of the change.
- [done] I updated/added relevant documentation (doc comments with `///`).
- [done] I rebased onto `main`.
- [done] I added new tests to check the change I am making, or this PR does not need tests.
- [done] I made sure all existing and new tests are passing.
- [done] I ran `dart format .` and committed any changes.
- [done] I ran `flutter analyze` …

fix typo in documentation

---

permission_handler_android/CHANGELOG.md
permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java
permission_handler_android/pubspec.yaml

In newer Android versions, permission dialogs can be dismissed. The OS does not give information to the application to determine whether the permission was explicitly denied, or if the dialog was dismissed. We used to check whether the permission was denied or permanently denied by checking the output of `shouldShowRational`. When dismissing the dialog, however, the result of `shouldShowRational` is the same as if the permission was permanently denied. We were therefore unable to distinguish whether the permission was denied permanently, or whether the user dismissed the dialog. Several reports emerged about this issue.
When reviewing this PR, please test all use cases to make sure the changes are correct. I went over all* of them, but it is important that a second person verifies that …

Fix 'Permanently denied' on permission dialog dismiss

---

permission_handler_platform_interface/CHANGELOG.md
permission_handler_platform_interface/lib/src/permissions.dart
permission_handler_platform_interface/pubspec.yaml

Clarifies the permission documentation on requesting background location permission through `Permission.locationAlways` on Android 10+ (API 29+).
Issue #781 is an instance of users being confused by how the permission works.

Clarify background location permission docs

---

permission_handler/CHANGELOG.md
permission_handler/README.md
permission_handler/pubspec.yaml

Adds a section to the FAQ on requesting background location permission through `Permission.locationAlways` on Android 10+ (API 29+).
Issue #781 is an instance of users being confused by how the permission works.

Add background location section to faq

---

permission_handler_android/CHANGELOG.md
permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionConstants.java
permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java
permission_handler_android/pubspec.yaml

When requesting the 'schedule exact alarm' permission, the user should be redirected to the application's setting screen where they can grant the permission. In the current version of the plugin, the `Intent` to open this screen is never fired. This PR adds the logic to open the screen and come back to the user with the result.
Closes #1137.

Open settings screen when requesting 'schedule exact alarm'

---

permission_handler_platform_interface/CHANGELOG.md
permission_handler_platform_interface/lib/src/permission_status.dart
permission_handler_platform_interface/lib/src/permissions.dart
permission_handler_platform_interface/pubspec.yaml

Android and iOS version constraints can be a tricky thing to take into account when developing using the `permission handler` plugin. It should be clear at a glance to developers which permissions can be used with which versions of Android or iOS. To that end, this PR updates the mentions of Android versions to follow a strict convention that should speak most to the mind of developers. The convention is 'Android $name (API $version)'. For example: 'Android 13 (API 33)' or 'Android Marshmallow (API 23)'. Both the public name and the API version are common ways of referring to Android versions. By listing them both, we cater to developers who are familiar with the names as they are presented to Android users, and to developers who are familiar with the API versions. Additionally, by …

Update Android version mentions in platform interface

---

permission_handler/CHANGELOG.md
permission_handler/README.md
permission_handler/pubspec.yaml

Android and iOS version constraints can be a tricky thing to take into account when developing using the `permission handler` plugin. It should be clear at a glance to developers which permissions can be used with which versions of Android or iOS. To that end, this PR updates the mentions of Android versions to follow a strict convention that should speak most to the mind of developers. The convention is 'Android $name (API $version)'. For example: 'Android 13 (API 33)' or 'Android Marshmallow (API 23)'. Both the public name and the API version are common ways of referring to Android versions. By listing them both, we cater to developers who are familiar with the names as they are presented to Android users, and to developers who are familiar with the API versions. Additionally, by …

Update Android version references in README

---

permission_handler/CHANGELOG.md
permission_handler/README.md
permission_handler/pubspec.yaml
permission_handler_android/CHANGELOG.md
permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionConstants.java
permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java
permission_handler_android/pubspec.yaml
permission_handler_platform_interface/CHANGELOG.md
permission_handler_platform_interface/lib/src/permission_status.dart
permission_handler_platform_interface/lib/src/permissions.dart
permission_handler_platform_interface/pubspec.yaml

Android distinguishes between [runtime permissions](https://developer.android.com/guide/topics/permissions/overview#runtime) and [special permissions](https://developer.android.com/guide/topics/permissions/overview#special). Runtime permissions give an app additional access to restricted data or let the app perform restricted actions that more substantially affect the system and other apps. These permissions present the user with a dialog where they can choose to grant or deny the permission. Special permissions guard access to system resources that are particularly sensitive or not directly related to user privacy. These permissions are requested by sending an `Intent` to the OS. The OS will open a special settings page where the user can grant the permission. Runtime permission request …

Handle special permissions correctly when requesting multiple permissions

---

permission_handler_android/CHANGELOG.md
permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/MethodCallHandlerImpl.java
permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionHandlerPlugin.java
permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java
permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java
permission_handler_android/pubspec.yaml

Currently there is a discrepancy between a permission's status and its request result. Permission statuses are always 'denied', even if the request result is 'permanently denied'. This PR fixes that bug by leveraging the logic added in #1125.
@mvanbeusekom do you agree that a permission's status should be able to return 'permanently denied'? I noticed statuses can also return 'restricted', so maybe you want to treat a permission's status and its request result differently? On iOS, the status always returns 'permanently denied' (note that permissions can only be asked once on iOS).
@mvanbeusekom should this change be labeled as breaking? Some folks might be depending on the exact return value of a permission's status.
This PR fixes #936. Note that the mentioned issue does not seem to be …

Return 'permanently denied' as permission status

---

permission_handler/CHANGELOG.md
permission_handler/pubspec.yaml

This PR will update the dependency on `permission_handler_android` to version 11.0.0 in order to pull in a couple of bugfixes.

Update Android dependency

---

permission_handler_android/CHANGELOG.md
permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java
permission_handler_android/pubspec.yaml

Reply already submitted in Android 13 while user request permissions (eg. post_notification, locations)
Fatal Exception: java.lang.RuntimeException
Failure delivering result ResultInfo{who=@android:requestPermissions:, request=24, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity: java.lang.IllegalStateException: Reply already submitted
io.flutter.embedding.engine.dart.DartMessenger$Reply.reply (DartMessenger.java:435)
io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success (MethodChannel.java:263)
com.baseflow.permissionhandler.g.a (Unknown Source:2)
com.baseflow.permissionhandler.n.onRequestPermissionsResult (PermissionManager.java:173) …

Reply already submitted in Android 13 while user request permissions

---

permission_handler_android/CHANGELOG.md
permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java
permission_handler_android/pubspec.yaml

fix/1158: Return permanentlyDenied for Permission.notification.status

---

permission_handler_android/CHANGELOG.md
permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java
permission_handler_android/pubspec.yaml

During the changes in #1157, an oversight unintentionally changed the behavior of the business logic for checking permission statuses. Special permissions were now always reported as 'denied'. This was caused because the logic at the end of the for loop is now always fired, where it was previously escaped for these special permissions.
Fixes #1165.

Fixes bug where special permission's status would always be 'denied'

---

permission_handler/CHANGELOG.md
permission_handler/lib/permission_handler.dart
permission_handler/pubspec.yaml
permission_handler/test/permission_handler_test.dart

This PR introduces a new style for checking permission status.
Before:
```dart
Future<bool> askPermission() async {
PermissionStatus status = await Permission.contacts.request();
if (status.isDenied) {
// Your code
} else if (status.isGranted) {
// Your code
} else if (status.isRestricted) {
// Your code
}
}
```
After:
```dart
Future<bool> askPermission() async {
await Permission.contacts
.onDeniedCallback(() {
// Your code
})
.onGrantedCallback(() {
// Your code
})
.onRestrictedCallback(() {
// Your code
})
.request();
}
```
In this updated code, the permission status checks have been replaced with a more concise style that leverages the `PermissionCallbacks` extension. This change simplifies the code and makes it more readable.
[Contributor Guide]: …

Refactor Permission Handling for Improved Readability

---

permission_handler_platform_interface/CHANGELOG.md
permission_handler_platform_interface/lib/src/permissions.dart
permission_handler_platform_interface/pubspec.yaml
permission_handler_platform_interface/test/src/method_channel/method_channel_permission_handler_test.dart
permission_handler_platform_interface/test/src/permissions_test.dart

Platform Interface: Deprecates `calendar`, introduces `calendarReadOnly` and `calendarFullAccess`

---

permission_handler_android/CHANGELOG.md
permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionConstants.java
permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java
permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java
permission_handler_android/example/android/app/src/main/AndroidManifest.xml
permission_handler_android/pubspec.yaml

Implements the `Permission.calendarReadOnly` and `Permission.calendarFullAccess` permissions.
The current architecture does not support the way Android deals with calendar permissions very well. As a refactor that removes almost all Java code is in the works, we decided not to care too much about the code quality.
Closes #1182.

Implement `Permission.calendarReadOnly` and `Permission.calendarFullAccess`

---

permission_handler_platform_interface/CHANGELOG.md
permission_handler_platform_interface/lib/src/permissions.dart
permission_handler_platform_interface/pubspec.yaml
permission_handler_platform_interface/test/src/method_channel/method_channel_permission_handler_test.dart

The calendar permission has been split into read-only and full access, as this split can be facilitated by Android's read/write split and iOS's read/full-access split. However, it turns out that iOS's calendar permissions are split in write/full-access instead. Therefore, the new calendar split for the app-facing package will be write-only and full access.

Replace `calendarReadOnly` with `calendarWriteOnly`

---

permission_handler_android/CHANGELOG.md
permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionConstants.java
permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java
permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java
permission_handler_android/pubspec.yaml

The calendar permission has been split into read-only and full access, as this split can be facilitated by Android's read/write split and iOS's read/full-access split. However, it turns out that iOS's calendar permissions are split in write/full-access instead. Therefore, the new calendar split for the app-facing package will be write-only and full access.

Update logic to handle calendar WRITE/FULL_ACCESS instead of READ/FULL_ACCESS

---

permission_handler_platform_interface/CHANGELOG.md
permission_handler_platform_interface/lib/src/permissions.dart
permission_handler_platform_interface/pubspec.yaml

Documentation is updated that resolves: [#944](https://github.com/Baseflow/flutter-permission-handler/issues/944). It was unclear how to use photo permission on Android on api 32 (Android 12) and below and api 33 (Android 13) and above.

Updates documentation for Permission.photos on Android

---

permission_handler_android/lib/permission_handler_android.dart
permission_handler_android/lib/src/android_object_mirrors/manifest.dart

Ports the `Manifest.permission` and `Manifest.permission_group` strings to Dart.
Users can now type:
```dart
Manifest.permission.READ_CALENDAR;
Manifest.permission_group.CALENDAR;
```
@mvanbeusekom: do we mirror Java code formatting? If not, above should be changed to:
```dart
Manifest.permission.readCalendar;
Manifest.permissionGroup.calendar;
```

Port Android `Manifest.permission` and `Manifest.permission_group`

---

permission_handler_android/CHANGELOG.md
permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java
permission_handler_android/pubspec.yaml

Fixes a bug where the `ignoreBatteryOptimizations` reports a denied status when requesting permission and the user granted permission.
Solves #1191

Report ignoreBatteryOptimizations permission correctly

---

permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/ActivityCompatHostApiImpl.java
permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionHandlerPigeon.java
permission_handler_android/lib/permission_handler_android.dart
permission_handler_android/lib/src/android_object_mirrors/activity_compat.dart
permission_handler_android/lib/src/android_object_mirrors/package_manager.dart
permission_handler_android/lib/src/android_permission_handler_api_impls.dart
permission_handler_android/lib/src/extensions.dart
permission_handler_android/lib/src/permission_handler.pigeon.dart
permission_handler_android/lib/src/permission_handler_android.dart
permission_handler_android/lib/src/utils.dart
permission_handler_android/pigeons/android_permission_handler.dart
permission_handler_android/pubspec.yaml
permission_handler_android/test/activity_compat_test.dart
permission_handler_android/test/permission_handler_test.dart
permission_handler_android/test/test_permission_handler.pigeon.dart
permission_handler_platform_interface/lib/src/permission_status.dart
permission_handler_platform_interface/test/src/permission_status_test.dart

Implements `checkPermissionStatus` for normal permissions.
This PR also includes:
- Clone of `PackageManager`
- Mapping of package `Permission`s to a list of Android permissions as listed in the manifest
- Dart implementation to determine the strictest `PermissionStatus`

`checkPermissionStatus` for normal permissions

---

permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/ActivityHostApiImpl.java
permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/ContextHostApiImpl.java
permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PackageManagerFlutterApiImpl.java
permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PackageManagerHostApiImpl.java
permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionHandlerPigeon.java
permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionHandlerPlugin.java
permission_handler_android/lib/src/android_object_mirrors/activity.dart
permission_handler_android/lib/src/android_object_mirrors/context.dart
permission_handler_android/lib/src/android_object_mirrors/package_manager.dart
permission_handler_android/lib/src/android_permission_handler_api_impls.dart
permission_handler_android/lib/src/permission_handler.pigeon.dart
permission_handler_android/lib/src/permission_handler_android.dart
permission_handler_android/pigeons/android_permission_handler.dart
permission_handler_android/test/test_permission_handler.pigeon.dart

Ports the necessary Android SDK bits for checking whether an application can request package installs.
Closes https://github.com/orgs/Baseflow/projects/9/views/1?pane=issue&itemId=39927253.

Refactor: Port `PackageManager.canRequestPackageInstalls` (Android)

---

permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/ActivityHostApiImpl.java
permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionHandlerPigeon.java
permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionHandlerPlugin.java
permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/SettingsHostApiImpl.java
permission_handler_android/lib/src/android_object_mirrors/activity.dart
permission_handler_android/lib/src/android_object_mirrors/context.dart
permission_handler_android/lib/src/android_object_mirrors/package_manager.dart
permission_handler_android/lib/src/android_object_mirrors/settings.dart
permission_handler_android/lib/src/android_permission_handler_api_impls.dart
permission_handler_android/lib/src/permission_handler.pigeon.dart
permission_handler_android/pigeons/android_permission_handler.dart
permission_handler_android/test/test_permission_handler.pigeon.dart

Ports the necessary Android SDK bits for checking whether an application can draw over the screen.
In the process, duplicate code for `Activity` that is present in `Context` was removed as much as possible.
Closes https://github.com/orgs/Baseflow/projects/9/views/1?pane=issue&itemId=39927286.

Refactor: Port `Settings.canDrawOverlays` (Android)

---

permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/ContextHostApiImpl.java
permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/NotificationManagerFlutterApiImpl.java
permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/NotificationManagerHostApiImpl.java
permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionHandlerPigeon.java
permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionHandlerPlugin.java
permission_handler_android/lib/permission_handler_android.dart
permission_handler_android/lib/src/android_object_mirrors/activity.dart
permission_handler_android/lib/src/android_object_mirrors/context.dart
permission_handler_android/lib/src/android_object_mirrors/notification_manager.dart
permission_handler_android/lib/src/android_object_mirrors/package_manager.dart
permission_handler_android/lib/src/android_object_mirrors/power_manager.dart
permission_handler_android/lib/src/android_permission_handler_api_impls.dart
permission_handler_android/lib/src/permission_handler.pigeon.dart
permission_handler_android/pigeons/android_permission_handler.dart
permission_handler_android/test/test_permission_handler.pigeon.dart

**Note**: This PR should be merged after #1216.
Ports the necessary Android SDK bits for checking whether an application access notification policies.
Closes: https://github.com/orgs/Baseflow/projects/9/views/1?pane=issue&itemId=39927317.

Refactor: Port `NotificationManager` (Android)

---

.github/workflows/permission_handler_apple.yaml

The current build step for iOS is named "Run Android build". This PR renames the step to reflect the correct platform and avoid confusion.

Rename build step to reflect correct platform

---

permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/EnvironmentHostApiImpl.java
permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionHandlerPigeon.java
permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionHandlerPlugin.java
permission_handler_android/lib/permission_handler_android.dart
permission_handler_android/lib/src/android_object_mirrors/environment.dart
permission_handler_android/lib/src/android_permission_handler_api_impls.dart
permission_handler_android/lib/src/permission_handler.pigeon.dart
permission_handler_android/pigeons/android_permission_handler.dart
permission_handler_android/test/test_permission_handler.pigeon.dart

Ports the necessary Android SDK bits for checking whether an application can manage external storage.
Closes https://github.com/orgs/Baseflow/projects/9/views/1?pane=issue&itemId=39927331.

Refactor: Port `Environment.isExternalStorageManager` (Android)

---

permission_handler_windows/CHANGELOG.md
permission_handler_windows/pubspec.yaml
permission_handler_windows/windows/permission_constants.h

This is the PR for updating the Windows package. It is part of @MilosKarakas's PR #1151.
iOS 17.0 introduces the notion of write-only and full-access calendar permissions. This PR builds on an earlier PR to the platform interface that makes this distinction (#1183, #1193), implementing the new permissions on Windows. Note that on Windows permissions are always given.
Fixes #1108.

Support iOS 17 calendar permissions (Windows)

---

permission_handler_html/CHANGELOG.md
permission_handler_html/pubspec.yaml

Bumps the version of the platform interface to v4. This is needed for updating the app-facing package to bring all platform updates regarding calendar permissions to end-users.

Web: bumps platform interface version

---

permission_handler/README.md

permission_handler's README.md file lists an incorrect permission for reading Android media on API 33 and above. This PR changes the `READ_MEDIA_VIDEOS` permission to `READ_MEDIA_VIDEO` (removing the `S`).
The relevant permission can be found at https://developer.android.com/reference/android/Manifest.permission#READ_MEDIA_VIDEO.
I have left some of these unchecked, as I believe that they aren't applicable to this contribution. Please let me know if I should change them.

[Permission Handler] Correct Android video permission name for API 33+

---

permission_handler_android/CHANGELOG.md
permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionHandlerPlugin.java
permission_handler_android/pubspec.yaml

The plugin keeps hold of the `PluginBinding` instance once an `Activity` is attached, but never releases the instance when the `Activity` is detached from the plugin. This will cause the `Activity` to be leaked (as described in issue #1256). This PR will release the `PluginBinding` instance when the `onDetachedFromActivity` method is called, making sure the handle to the `Activity` is released, which prevents leaking the `Activity`.
Fixes #1259 

Release PluginBinding instance when activity is detached.

---

README.md

Fixed spelling error in read me: 
- Instructions on how to implement a platform packages can be found **int the** [README.md][4] of the `permission_handler_platform_interface` package.
Changed to:
- Instructions on how to implement a platform packages can be found **in the** [README.md][4] of the `permission_handler_platform_interface` package.

Corrected README.md spelling

---

permission_handler_apple/ios/permission_handler_apple.podspec

Updated version in the podspec file as it seems like this bump was overlooked after 9.1.1 release. Bumping as it was confusing for me use the latest version of the plugin and still seeing `9.1.1` in the podfile.lock of iOS part of the project I am working on.
Probably, this would need a bump to `9.3.1` for the next release, but as I don't know about plans on which version goes next bumping only to the latest at the moment.
Note, I didn't check most of points in the provided checklist as this change doesn't really affects anything from functionality point.

Update version permission_handler_apple.podspec to avoid confusion

---

permission_handler/CHANGELOG.md
permission_handler/README.md
permission_handler/pubspec.yaml
permission_handler_apple/CHANGELOG.md
permission_handler_apple/ios/Classes/PermissionHandlerEnums.h
permission_handler_apple/pubspec.yaml

*Replace this paragraph with a short description of what issue this pull request (PR) solves and provide a description of the change.  Consider including before/after screenshots.*
The to be commented out comment for only adding photos to the library under iOS (NSPhotoLibraryAddUsageDescription) was missing in the README.
#980

Add `photosAddOnly` setup for iOS to Podfile in README

---

permission_handler_apple/CHANGELOG.md
permission_handler_apple/ios/Resources/PrivacyInfo.xcprivacy
permission_handler_apple/ios/permission_handler_apple.podspec
permission_handler_apple/pubspec.yaml

Adds the required privacy manifest to the iOS implementation.
Because the permission_handler_apple package doesn't collect any privacy data, the privacy manifest can be empty. 
Note that we are following the standard Flutter / Cocoapods implementation which has the following caveat:
> The large caveat is that we do not currently know if this actually works. This is the method of inclusion that seems to be [the consensus among people using Cocoapods](https://github.com/CocoaPods/CocoaPods/issues/10325), as bundling it directly as a `resource` causes problems for clients who do not use `use_frameworks`. (In theory it seems like a manifest would not actually be *required* in that case since there is no framework, but it has the potential to actually stomp top-level resources.) Hopefully the …

Adds iOS privacy manifest.

---

permission_handler_apple/CHANGELOG.md
permission_handler_apple/ios/Resources/PrivacyInfo.xcprivacy
permission_handler_apple/pubspec.yaml

Updates the privacy manifest to include the use of the `NSUserDefaults` API. 
The permission_handler stores a boolean value to track if permission to always 
access the device location has been requested.
Resolves #1292

Add the use of NSUserDefaults to privacy manifest.

---

permission_handler_apple/CHANGELOG.md
permission_handler_apple/example/ios/Podfile
permission_handler_apple/example/ios/Runner.xcodeproj/project.pbxproj
permission_handler_apple/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
permission_handler_apple/ios/Classes/PermissionHandlerPlugin.m
permission_handler_apple/ios/Classes/PermissionManager.h
permission_handler_apple/ios/Classes/PermissionManager.m
permission_handler_apple/ios/Classes/strategies/AppTrackingTransparencyPermissionStrategy.m
permission_handler_apple/ios/Classes/strategies/AssistantPermissionStrategy.m
permission_handler_apple/ios/Classes/strategies/AudioVideoPermissionStrategy.m
permission_handler_apple/ios/Classes/strategies/BackgroundRefreshStrategy.m
permission_handler_apple/ios/Classes/strategies/BluetoothPermissionStrategy.m
permission_handler_apple/ios/Classes/strategies/ContactPermissionStrategy.m
permission_handler_apple/ios/Classes/strategies/CriticalAlertsPermissionStrategy.m
permission_handler_apple/ios/Classes/strategies/EventPermissionStrategy.m
permission_handler_apple/ios/Classes/strategies/LocationPermissionStrategy.h
permission_handler_apple/ios/Classes/strategies/LocationPermissionStrategy.m
permission_handler_apple/ios/Classes/strategies/MediaLibraryPermissionStrategy.m
permission_handler_apple/ios/Classes/strategies/NotificationPermissionStrategy.m
permission_handler_apple/ios/Classes/strategies/PermissionStrategy.h
permission_handler_apple/ios/Classes/strategies/PhonePermissionStrategy.m
permission_handler_apple/ios/Classes/strategies/PhotoPermissionStrategy.m
permission_handler_apple/ios/Classes/strategies/SensorPermissionStrategy.m
permission_handler_apple/ios/Classes/strategies/SpeechPermissionStrategy.m
permission_handler_apple/ios/Classes/strategies/StoragePermissionStrategy.m
permission_handler_apple/ios/Classes/strategies/UnknownPermissionStrategy.m
permission_handler_apple/pubspec.yaml

* Adds the `PERMISSION_LOCATION_WHENINUSE` marco, which can be used instead of
the `PERMISSION_LOCATION` macro and only enable the `requestWhenInUseAuthorization`
and remove the `requestAlwaysAuthorization` when requesting location permission.
* Improves error handling when `Info.plist` doesn't contain the correct declarations.
* Adds support for the `NSLocationAlwaysAndWhenInUseUsageDescription` property list
key.

Adds support for when in use only.

---

permission_handler_apple/CHANGELOG.md
permission_handler_apple/ios/Classes/PermissionHandlerEnums.h
permission_handler_apple/pubspec.yaml

A typo in the enum file can lead to confusing bugs if plugin users paste that into their plist. This PR fixes that typo.

Fix typo in comment for full calendar access

---

permission_handler_apple/CHANGELOG.md
permission_handler_apple/ios/Classes/strategies/EventPermissionStrategy.m
permission_handler_apple/pubspec.yaml

This method is causing a compilation warning: -Wint-conversion.
Even ignoring the warning, the nil value would not be tolerated and is never actually returned.

Fix possible-nil return type of EventPermissionStrategy#getEntityType

---

permission_handler_platform_interface/CHANGELOG.md
permission_handler_platform_interface/lib/src/method_channel/method_channel_permission_handler.dart
permission_handler_platform_interface/pubspec.yaml

Resolves the `Unhandled Exception: type 'int' is not a subtype of type 'FutureOr'` that occurred when calling the `shouldShowRequestPermissionRationale` on iOS.

Resolve unhandled exception on iOS

---

permission_handler_android/CHANGELOG.md
permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionHandlerPlugin.java
permission_handler_android/pubspec.yaml

The Flutter team is removing references to the Android V1 embedding from their code base (see flutter/flutter#144726). This would mean that code still containing references to the Android V1 embedding will no longer compile. 
This PR removes references to Android V1 embedding from the permission_handler_android plugin.
- flutter/flutter#144726

Removes  references to Android v1 embedding.

---

permission_handler_android/CHANGELOG.md
permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionHandlerPlugin.java
permission_handler_android/pubspec.yaml

Follow up to https://github.com/Baseflow/flutter-permission-handler/pull/1318.
Tested with `flutter run --debug` with the changes from https://github.com/flutter/engine/pull/52022 applied locally.
https://github.com/Baseflow/flutter-permission-handler/issues/1335

Remove additional Android v1 embedding class reference.

---

permission_handler_platform_interface/CHANGELOG.md
permission_handler_platform_interface/lib/src/permission_status.dart
permission_handler_platform_interface/lib/src/permissions.dart
permission_handler_platform_interface/pubspec.yaml

Patch update for the PR #1347, includes changes required in `permission_handler_platform_interface`.

Added limited access permission for android 14+

---

permission_handler_android/CHANGELOG.md
permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java
permission_handler_android/pubspec.yaml

Fixes a bug that causes a `NullPointerException` when the application is restarted after being killed by Android during the request of special permissions (like, `Permission.ignoreBatteryOptimizations`, `Permission.systemAlertWindow`, `Permission.accessNotificationPolicy`, `Permission.scheduleExactAlarm` and `Permission.manageExternalStorage`).
- Fixes #1360 
- Fixes #968 
- Fixes #807
- Closes #1346 

Fix issue 1360

---

permission_handler_html/CHANGELOG.md
permission_handler_html/lib/web_delegate.dart
permission_handler_html/pubspec.yaml

While migrating to the `package:web`, `PermissionDescriptior` was not passed when checking the permission status causing it to throw an exception and not give the expected output i.e. the status of the requested permission.
Before this fix, following error was thrown when checking the permission status:
After the fix, the permission status is shown accurately:
This PR fixes issue #1353 .

Fix: PermissionDescriptor Error while checking the permission status on web

---

permission_handler_android/CHANGELOG.md
permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java
permission_handler_android/pubspec.yaml

This PR fixes the issue https://github.com/Baseflow/flutter-permission-handler/issues/1243
Before fix when selecting 'Selected Photos Access enabled' on Android 14 the code
`await Permission.photos.request();`
returned `PermissionStatus.denied`. After fix it returns `PermissionStatus.limited`

Fix: Return correct permission status for Android's limited media access

---

permission_handler_html/CHANGELOG.md
permission_handler_html/lib/web_delegate.dart
permission_handler_html/pubspec.yaml

web 1.0.0 removed `PermissionDescriptor`: https://github.com/dart-lang/web/commit/7604578eb538c471d438608673c037121d95dba5#diff-6f4c7956b6e25b547b16fc561e54d5e7d520d2c79a59ace4438c60913cc2b1a2L35-L40 - I have simply copied it over to this project.
* Fixes #1363

fix compile error with web 1.0 #1363

---

permission_handler/README.md
permission_handler/example/ios/Podfile
permission_handler_apple/example/ios/Podfile

Update the link to the PermissionHandlerEnums.h
- https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler_apple/ios/Classes/PermissionHandlerEnums.h

Fix link to PermissionHandlerEnums.h

---

permission_handler_platform_interface/CHANGELOG.md
permission_handler_platform_interface/lib/src/permissions.dart

Removed the plural 's' of the class name references at the photos (9) permission description.

Fix: Correct class name references

---

permission_handler_html/CHANGELOG.md
permission_handler_html/lib/permission_handler_html.dart
permission_handler_html/pubspec.yaml

*Replace this paragraph with a short description of what issue this pull request (PR) solves and provide a description of the change.  Consider including before/after screenshots.*
- #1382

fix: don't crash on safari<16

---

.github/workflows/permission_handler_android.yaml
permission_handler_android/CHANGELOG.md
permission_handler_android/android/build.gradle
permission_handler_android/example/android/app/build.gradle
permission_handler_android/example/android/build.gradle
permission_handler_android/example/android/gradle/wrapper/gradle-wrapper.properties
permission_handler_android/example/android/settings.gradle
permission_handler_android/pubspec.yaml

Updates the minimum supported Android SDK version to 19 (from 16). 
Also migrates the example app away from the use of imperative plugin apply in Gradle (see: https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply).
Solves #1396 

Depend on the min SDK version of Flutter installation

---

permission_handler_html/CHANGELOG.md
permission_handler_html/lib/permission_handler_html.dart
permission_handler_html/pubspec.yaml

This PR fixes the bug mentioned here:
https://github.com/Baseflow/flutter-permission-handler/issues/1386
It seems that "mediaDevices" is only available when using https or localhost, but not when using e.g. http://0.0.0.0. Thus it is necessary to check if "mediaDevices" exists before accessing it.

Bug fix for the DartError: TypeError: null: type 'Null' is not a subtype of type 'JSObject'

---

permission_handler_html/CHANGELOG.md
permission_handler_html/lib/permission_handler_html.dart
permission_handler_html/pubspec.yaml

To fix https://github.com/Baseflow/flutter-permission-handler/issues/1409 I have changed the way how "mediaDevices" is loaded to make it compatible with WASM. Basically I am just using the same method now that was used for "permissions" a few lines below. It still seems to work fine for me regarding the bug https://github.com/Baseflow/flutter-permission-handler/issues/1386 .

Bug fix for WASM compilation

---

.github/workflows/permission_handler.yaml
.github/workflows/permission_handler_apple.yaml
permission_handler/example/lib/main.dart
permission_handler/example/pubspec.yaml
permission_handler/lib/permission_handler.dart
permission_handler_apple/CHANGELOG.md
permission_handler_apple/example/lib/main.dart
permission_handler_apple/example/pubspec.yaml
permission_handler_apple/ios/Classes/strategies/ContactPermissionStrategy.m
permission_handler_apple/pubspec.yaml

The package wasn't currently handling the new `CNAuthorizationStatusLimited` introduce in ios18. Older versions of ios will remain unchanged. Here's a screen recording showcasing the change
- ios 17.2
https://github.com/user-attachments/assets/4ec5422a-cd72-4c14-bf5e-3a7227148e38
- ios 18.0
https://github.com/user-attachments/assets/2a6c5c56-dc16-41b9-977e-1167462d8d7a
- https://github.com/Baseflow/flutter-permission-handler/issues/1387
- https://github.com/Baseflow/flutter-permission-handler/issues/1376

Handle contacts limited permission

---

permission_handler_apple/CHANGELOG.md
permission_handler_apple/ios/Classes/PermissionManager.m
permission_handler_apple/ios/Classes/strategies/AssistantPermissionStrategy.m
permission_handler_apple/ios/Classes/strategies/BluetoothPermissionStrategy.m
permission_handler_apple/ios/Classes/strategies/ContactPermissionStrategy.m
permission_handler_apple/ios/Classes/strategies/LocationPermissionStrategy.m
permission_handler_apple/ios/Classes/strategies/MediaLibraryPermissionStrategy.m
permission_handler_apple/ios/Classes/strategies/NotificationPermissionStrategy.m
permission_handler_apple/ios/Classes/strategies/SensorPermissionStrategy.m
permission_handler_apple/ios/Classes/strategies/SpeechPermissionStrategy.m
permission_handler_apple/pubspec.yaml

iOS versions < 11 haven't been supported since Flutter 3.3, which is over two years old. Even that version is too old to be able to ship to the App store with (as it lacks a privacy manifest), so there is no clear value in continuing to support versions even older than that.
This updates the Flutter SDK constraint to 3.3, where iOS 11 became the minimum, and removes all `@available` checks related to iOS 11 or earlier, as well as any fallback code that only ran on versions older than that.
Fixes https://github.com/Baseflow/flutter-permission-handler/issues/1455

Drop support for iOS < 11

---

permission_handler/CHANGELOG.md
permission_handler/README.md
permission_handler/example/ios/Flutter/AppFrameworkInfo.plist
permission_handler/example/ios/Podfile
permission_handler/example/ios/Runner.xcodeproj/project.pbxproj
permission_handler/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
permission_handler/example/ios/Runner/AppDelegate.swift
permission_handler/pubspec.yaml

Updates iOS example project IPHONEOS_DEPLOYMENT_TARGET from 11.0 to 12.0 and README documentation about compileSDKversion 33 to 35.

updated bug in README documentation about the compileSDK version

---

permission_handler/README.md
permission_handler_apple/example/ios/Podfile

docs(README): Update the correspondence between permission groups and the key values of Info.plist
- The correspondence table between permission groups and Info.plist key values has been updated in the README file
- Several new mapping relationships for permission groups have been added, including sensors, bluetooth, appTrackingTransparency, criticalAlerts, and assistant
- Corrected the macro definitions of some permission groups

docs(README): Update the correspondence between permission groups and the key values of Info.plist
