.gitattributes
README.md

Add kotlin as language for github

---

pubspec.yaml

Bug
Running `flutter packages pub publish --dry-run` results in errors
Fix the reported errors
No
Run `flutter packages pub publish --dry-run`

Add SDK version constraints

---

CHANGELOG.md
ios/permission_handler.podspec
pubspec.yaml

Prepare for version 1.0.0 of the Permission plugin

Bumb version number and update changelog

---

CHANGELOG.md
README.md
example/lib/main.dart
ios/permission_handler.podspec
lib/permission_handler.dart
pubspec.yaml

Feature. You can now override or make a new instance of the plugin
All methods are static
Not anymore
Yes

Make methods non static

---

android/build.gradle
example/android/app/build.gradle
example/android/build.gradle
example/android/gradle/wrapper/gradle-wrapper.properties
example/lib/main.dart

Maintenance
The project uses outdated versions of Kotlin and Gradle
Updated the dependencies on Kotlin and Gradle
No
Compile the Android example project:
```shell
cd example
flutter build apk
```
-

Update Kotlin and Gradle

---

CHANGELOG.md
README.md
ios/permission_handler.podspec
pubspec.yaml

Bumbed versionnumbers and updated changelog

---

CHANGELOG.md
README.md
ios/permission_handler.podspec
pubspec.yaml

Bumped version number to 2.1.2 and updated changelog

Bump version number

---

analysis_options.yaml
example/ios/Runner.xcodeproj/project.pbxproj
lib/permission_handler.dart
lib/utils/codec.dart
pubspec.yaml

Updates the flutter analyzes options to match with the latest specs.

Update analyze options configuration

---

.travis.yml
CHANGELOG.md
README.md
android/src/main/kotlin/com/baseflow/permissionhandler/PermissionHandlerPlugin.kt
android/src/main/kotlin/com/baseflow/permissionhandler/data/ServiceStatus.kt
android/src/main/kotlin/com/baseflow/permissionhandler/utils/Codec.kt
example/ios/Runner.xcodeproj/project.pbxproj
example/lib/main.dart
ios/Classes/PermissionManager.swift
ios/Classes/SwiftPermissionHandlerPlugin.swift
ios/Classes/data/ServiceStatus.swift
ios/Classes/strategies/AudioVideoPermissionStrategy.swift
ios/Classes/strategies/ContactPermissionStrategy.swift
ios/Classes/strategies/EventPermissionStrategy.swift
ios/Classes/strategies/LocationPermissionStrategy.swift
ios/Classes/strategies/MediaLibraryPermissionStrategy.swift
ios/Classes/strategies/PermissionStrategy.swift
ios/Classes/strategies/PhotoPermissionStrategy.swift
ios/Classes/strategies/SensorPermissionStrategy.swift
ios/Classes/strategies/SpeechPermissionStrategy.swift
ios/Classes/strategies/UnknownPermissionStrategy.swift
ios/Classes/utils/Codec.swift
ios/permission_handler.podspec
lib/permission_enums.dart
lib/permission_handler.dart
lib/utils/codec.dart
pubspec.yaml
scripts/before_build_apks.sh
scripts/before_build_ipas.sh

Feature
Currently there is not clear way to check if the location services (on Android and iOS) or the motion services (iOS only) are enabled/ disabled.
Added a new API method which can be used to check the state of the above mentioned services.
No
Run the example app and click the ! icon for one of the permissions.

 Added option to check service status

---

example/pubspec.yaml
pubspec.yaml

Maintenance
Flutter analyze returns warning:
```
info: The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions. (sdk_version_async_exported_from_core at [flutter_25724_jumpto_0_refresh] lib/main.dart:26)
```
See also: https://github.com/flutter/flutter/issues/26179
Upgraded the Dart environment to version >=2.1.0 <3.0.0
No
Run `flutter analyze` in the root of the project.
- https://github.com/flutter/flutter/issues/26179

Set the Dart SDK to version >=2.1.0 <3.0.0

---

android/src/main/java/com/baseflow/permissionhandler/PermissionHandlerPlugin.java

Bugfix
Crashes / causes Flutter result errors when requesting multiple permissions, e.g. via multi touch in the sample app.
Fixes the behavior.
No.
Example App multi touch,
#23 .

Add a missing return statement after a result.error response is sent.

---

README.md
example/android/app/src/debug/AndroidManifest.xml
example/android/app/src/main/AndroidManifest.xml
example/android/app/src/profile/AndroidManifest.xml
example/ios/Runner/Info.plist

Documentation updatge
Usage of permissions options in AndroidManifest or Info.plist is unclear.
Clarify the usage of permissions option in AndroidManifest of Info.plist
No
N/A
- Fixes #149

Improved documentation regarding permission options

---

CONTRIBUTING.md
README.md
android/src/main/java/com/baseflow/permissionhandler/PermissionHandlerPlugin.java
example/ios/Runner/Runner.entitlements
ios/Classes/PermissionHandlerEnums.h
ios/Classes/PermissionManager.h
ios/Classes/PermissionManager.m
ios/Classes/strategies/NotificationPermissionStrategy.h
ios/Classes/strategies/NotificationPermissionStrategy.m
lib/src/permission_enums.dart

It's a feature.
It can not check and request notification permission.
Support check and request notification permission
No.

Add notification feature

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.md

Documentation update
Documentation references the outdated Github organization.
Update to use the correct organization and fix all URL references.
No

Update Github URL

---

analysis_options.yaml
example/lib/main.dart
lib/src/permission_enums.dart
lib/src/permission_handler.dart
lib/src/utils/codec.dart
pubspec.yaml

Documentation update
Some of the public API methods are not documented.
The complete public API is documented. Also added linter rules to help alert developers to document future features.
No
Run `flutter analyze .` and see that it doesn't warn for plugic members missing documentation.
#216

Document public api

---

android/src/main/java/com/baseflow/permissionhandler/PermissionHandlerPlugin.java

I have made a few changes so that I can query the permission even without the gps active.
Perhaps this is a solution that interests others

Request Location-Permission without active GPS

---

android/src/main/java/com/baseflow/permissionhandler/PermissionHandlerPlugin.java

https://github.com/Baseflow/flutter-permission-handler/issues/119

Fix cast issue

---

permission_handler/android/src/main/java/com/baseflow/permissionhandler/ServiceManager.java

Bugfix.
See issue #235.
Returns correct location status again.
No.
- Get a Android 4.4,5,6,7,8 phone.
- Disable Location Services
- Test the function in the example
fixes #235

Resolve ServiceManager issue for Android 4.4+ to <Pie

---

permission_handler/lib/permission_handler.dart
permission_handler/pubspec.yaml

Hotfix for the issue mentioned in https://github.com/Baseflow/flutter-permission-handler/issues/230#issuecomment-605673131

Fix extension method export

---

permission_handler/android/src/main/java/com/baseflow/permissionhandler/MethodCallHandlerImpl.java
permission_handler/android/src/main/java/com/baseflow/permissionhandler/PermissionHandlerPlugin.java

4.4.0+hotfix.2 bg fix

---

README.md

Bugfix to #294
Link not shown
Link is now visible
No
None

Minor readme bug fix for issue #294

---

permission_handler_platform_interface/lib/src/permissions.dart

Bug fix.
Can not determine the phone service status.

.phone is a permission with a service

---

permission_handler/CHANGELOG.md
permission_handler/ios/permission_handler.podspec
permission_handler/lib/permission_handler.dart
permission_handler/pubspec.yaml
permission_handler_platform_interface/lib/src/permissions.dart

Bug fix.
Can not determine the phone service status.
No

Phone permission with service

---

README.md

Fix AndroidManifest example link

Fix AndroidManifest example link

---

README.md

docs update
CONTRIBUTING.md is not found as it was redirected to the wrong location.
No
Click on the CONTRIBUTING.md

fix href link

---

permission_handler_platform_interface/CHANGELOG.md
permission_handler_platform_interface/lib/src/method_channel/method_channel_permission_handler.dart
permission_handler_platform_interface/pubspec.yaml

Null safety support for the platform interface
Not null safe
Null safe

Nullsafe platform interface

---

permission_handler/CHANGELOG.md
permission_handler/example/ios/Flutter/Flutter.podspec
permission_handler/example/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
permission_handler/example/lib/main.dart
permission_handler/example/lib/plugin_example/permission_widget.dart
permission_handler/example/lib/template/info_page.dart
permission_handler/example/pubspec.yaml
permission_handler/lib/permission_handler.dart
permission_handler/pubspec.yaml
permission_handler_platform_interface/pubspec.yaml

Null safety
Not null safe
Null safe
No

Nullsafety

---

permission_handler/CHANGELOG.md
permission_handler/android/build.gradle
permission_handler/android/src/main/java/com/baseflow/permissionhandler/PermissionHandlerPlugin.java

Fixes deprecation warnings when building on Android.
Resolves #473

Fix deprecation warning

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/app_facing_package.yaml
.github/workflows/platform_interface_package.yaml
README.md
permission_handler/CHANGELOG.md
permission_handler/android/src/main/java/com/baseflow/permissionhandler/PermissionConstants.java
permission_handler/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java
permission_handler/android/src/main/java/com/baseflow/permissionhandler/PermissionUtils.java
permission_handler/android/src/main/java/com/baseflow/permissionhandler/ServiceManager.java
permission_handler/example/android/app/src/main/AndroidManifest.xml
permission_handler/ios/Classes/PermissionHandlerEnums.h
permission_handler/ios/Classes/PermissionManager.h
permission_handler/ios/Classes/PermissionManager.m
permission_handler/ios/Classes/strategies/BluetoothPermissionStrategy.h
permission_handler/ios/Classes/strategies/BluetoothPermissionStrategy.m
permission_handler/pubspec.yaml
permission_handler_platform_interface/CHANGELOG.md
permission_handler_platform_interface/lib/src/permissions.dart
permission_handler_platform_interface/pubspec.yaml

Feature
Currently the CI/CD workflow doesn't execute unit tests nor uploads code coverage results to codecov.io
This pull request adds support for running unit tests and uploads code coverage information to codecov.io.
No
n/a
n/a

Support codecov workflow

---

README.md

docs update. just added the missing comma.

Fix typo about missing comma in ReadMe

---

permission_handler/CHANGELOG.md

Fixed some typos in the permission_handler CHANGELOG.md
No

Fixed typos

---

permission_handler/README.md

docs update
bluetooth is missing in the package readme
added bluetooth in the right readme
no

Update readme with bluetooth

---

permission_handler/example/android/app/src/main/AndroidManifest.xml

Bug fix.
Build is broken.
Build passes.
No.
If CI passes, this should be good, as it was not passing before.
#790

Fixed issue with deprecated Android v1 embedding.

---

permission_handler/example/pubspec.yaml
permission_handler_android/example/pubspec.yaml
permission_handler_apple/example/pubspec.yaml
permission_handler_windows/example/pubspec.yaml

Bug fix
The example project contains a dependency based on a Git URL which uses the git:// protocol unauthenticated. This is no longer supported and causes the tree to fail.
Updated the Git dependency to use the `https` protocol.
No

Update URL on git dependency in example project

---

permission_handler_android/android/build.gradle
permission_handler_android/example/android/app/build.gradle

Add compatibility with Android Gradle Plugin 8.0

---

permission_handler_html/test/permission_handler_web_test.dart

#1226 contained an error and should not have been merged. This PR is a follow-up that will rectify this mistake.

Follow-up to: Modernize web package and rename to permission_handler_html

---

permission_handler_html/CHANGELOG.md
permission_handler_html/example/lib/main.dart
permission_handler_html/lib/permission_handler_html.dart
permission_handler_html/lib/web_delegate.dart
permission_handler_html/pubspec.yaml

This should fix https://github.com/Baseflow/flutter-permission-handler/issues/1239

Html non secure permissions

---

.github/workflows/permission_handler_android.yaml
permission_handler_android/CHANGELOG.md
permission_handler_android/android/build.gradle
permission_handler_android/android/gradle.properties
permission_handler_android/example/android/app/build.gradle
permission_handler_android/example/android/build.gradle
permission_handler_android/example/android/gradle.properties
permission_handler_android/example/android/gradle/wrapper/gradle-wrapper.properties
permission_handler_android/pubspec.yaml

Updates Gradle and the Android Gradle Plugin to version 8.0.0.

Upgrade Gradle and AGP and move from imperative plugin apply.

---

permission_handler_android/CHANGELOG.md
permission_handler_android/android/src/main/java/com/baseflow/permissionhandler/PermissionManager.java
permission_handler_android/pubspec.yaml

I adjusted the return of permission status; Added Android version version judgment

perf:Optimize the status of READ_MEDIA_VISUAL_USER_SELECTED permission

---

permission_handler_html/CHANGELOG.md
permission_handler_html/pubspec.yaml

This PR updates packages that depend on package:web to web: ">=0.5.1 <2.0.0".

Update package:web to ">=0.5.1 <2.0.0"

---

permission_handler/CHANGELOG.md
permission_handler/pubspec.yaml

Updates Android dependency to version 13 and higher. Updates android compileSDK to 35.

Updates Android dependency to ^13.0.0
